// Generated by gencpp from file lab3/ballLandInfo.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_BALLLANDINFO_H
#define LAB3_MESSAGE_BALLLANDINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lab3
{
template <class ContainerAllocator>
struct ballLandInfo_
{
  typedef ballLandInfo_<ContainerAllocator> Type;

  ballLandInfo_()
    : header()
    , x(0.0)
    , y(0.0)
    , distance(0.0)
    , type(0)  {
    }
  ballLandInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , distance(0.0)
    , type(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _distance_type;
  _distance_type distance;

   typedef uint32_t _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::lab3::ballLandInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab3::ballLandInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ballLandInfo_

typedef ::lab3::ballLandInfo_<std::allocator<void> > ballLandInfo;

typedef boost::shared_ptr< ::lab3::ballLandInfo > ballLandInfoPtr;
typedef boost::shared_ptr< ::lab3::ballLandInfo const> ballLandInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab3::ballLandInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab3::ballLandInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lab3': ['/home/odroid/catkin_ws/src/fanboat/src/lab3/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ballLandInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ballLandInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::ballLandInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::ballLandInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ballLandInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ballLandInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab3::ballLandInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76fc4f8b957047da4a6674b91860ee82";
  }

  static const char* value(const ::lab3::ballLandInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76fc4f8b957047daULL;
  static const uint64_t static_value2 = 0x4a6674b91860ee82ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab3::ballLandInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab3/ballLandInfo";
  }

  static const char* value(const ::lab3::ballLandInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab3::ballLandInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
#the x and y position of the object being targeted\n\
float64 x\n\
float64 y\n\
\n\
#how far the object being targeted is\n\
float64 distance\n\
\n\
#what type of object is being targeted 1 for ball 0 for landmark\n\
uint32 type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lab3::ballLandInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab3::ballLandInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.distance);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ballLandInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab3::ballLandInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab3::ballLandInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB3_MESSAGE_BALLLANDINFO_H
