<<<<<<< HEAD
// Generated by gencpp from file ball_detector/ballLocation.msg
// DO NOT EDIT!
=======
/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/fanboat/src/ball_detector/msg/ballLocation.msg
 *
 */
>>>>>>> 8f00e7774a103ee680e8144a155c28aad7a2b6cf


#ifndef BALL_DETECTOR_MESSAGE_BALLLOCATION_H
#define BALL_DETECTOR_MESSAGE_BALLLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ball_detector
{
template <class ContainerAllocator>
struct ballLocation_
{
  typedef ballLocation_<ContainerAllocator> Type;

  ballLocation_()
    : header()
    , imageWidth(0)
    , imageHeight(0)
    , x(0.0)
    , y(0.0)
    , radius(0.0)
    , distance(0.0)  {
    }
  ballLocation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , imageWidth(0)
    , imageHeight(0)
    , x(0.0)
    , y(0.0)
    , radius(0.0)
    , distance(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _imageWidth_type;
  _imageWidth_type imageWidth;

   typedef uint32_t _imageHeight_type;
  _imageHeight_type imageHeight;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _radius_type;
  _radius_type radius;

   typedef double _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::ball_detector::ballLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ball_detector::ballLocation_<ContainerAllocator> const> ConstPtr;

}; // struct ballLocation_

typedef ::ball_detector::ballLocation_<std::allocator<void> > ballLocation;

typedef boost::shared_ptr< ::ball_detector::ballLocation > ballLocationPtr;
typedef boost::shared_ptr< ::ball_detector::ballLocation const> ballLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ball_detector::ballLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ball_detector::ballLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ball_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
<<<<<<< HEAD
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ball_detector': ['/home/odroid/catkin_ws/src/fanboat/src/ball_detector/msg']}
=======
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ball_detector': ['/home/viki/catkin_ws/src/fanboat/src/ball_detector/msg']}
>>>>>>> 8f00e7774a103ee680e8144a155c28aad7a2b6cf

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ball_detector::ballLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_detector::ballLocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_detector::ballLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_detector::ballLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_detector::ballLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_detector::ballLocation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ball_detector::ballLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36109cf6193b8898954fb93e4e714a44";
  }

  static const char* value(const ::ball_detector::ballLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36109cf6193b8898ULL;
  static const uint64_t static_value2 = 0x954fb93e4e714a44ULL;
};

template<class ContainerAllocator>
struct DataType< ::ball_detector::ballLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ball_detector/ballLocation";
  }

  static const char* value(const ::ball_detector::ballLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ball_detector::ballLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
#The iamge width and height in pixels\n\
uint32 imageWidth\n\
uint32 imageHeight\n\
\n\
#The location of the ball center in x,y (width,height)\n\
float64 x\n\
float64 y\n\
#The radius of the detected ball\n\
float64 radius\n\
#The distance from the ball\n\
float64 distance\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ball_detector::ballLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ball_detector::ballLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.imageWidth);
      stream.next(m.imageHeight);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ballLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ball_detector::ballLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ball_detector::ballLocation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "imageWidth: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.imageWidth);
    s << indent << "imageHeight: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.imageHeight);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALL_DETECTOR_MESSAGE_BALLLOCATION_H
